"""HTML report generator for immune system performance.

Produces self-contained HTML reports with embedded CSS for
benchmark results, training progress, and system metrics.
"""

import json
import os
from datetime import datetime, timezone
from typing import Any

from core.logger import setup_logger

logger = setup_logger("reports")

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")


def _bar_html(label: str, value: float, max_value: float = 100.0,
              color: str = "#1a73e8", width: int = 300) -> str:
    """Render a single horizontal bar as HTML/CSS."""
    pct = min(value / max_value * 100, 100) if max_value > 0 else 0
    return f"""<div style="display:flex;align-items:center;margin:4px 0;gap:8px">
    <span style="width:140px;font-size:0.8rem;color:#536471;text-align:right;flex-shrink:0">{label}</span>
    <div style="flex:1;height:20px;background:#e8eaed;border-radius:10px;overflow:hidden;max-width:{width}px">
        <div style="height:100%;width:{pct:.0f}%;background:{color};border-radius:10px;transition:width 0.3s"></div>
    </div>
    <span style="width:50px;font-size:0.8rem;font-weight:600;color:#0f1419">{value:.1f}%</span>
</div>"""


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, 'Inter', 'Segoe UI', sans-serif; background: #f0f2f5; color: #0f1419; padding: 20px; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  .header {{ background: linear-gradient(135deg, #0f1419, #1a1d23); border-radius: 14px; padding: 24px 32px; margin-bottom: 20px; color: white; }}
  .header h1 {{ font-size: 1.5rem; font-weight: 800; letter-spacing: -0.03em; }}
  .header p {{ color: rgba(255,255,255,0.6); font-size: 0.85rem; margin-top: 4px; }}
  .card {{ background: white; border-radius: 12px; padding: 20px 24px; margin-bottom: 16px; border: 1px solid #e8eaed; }}
  .card h2 {{ font-size: 1.1rem; font-weight: 700; margin-bottom: 12px; color: #0f1419; }}
  .stat-row {{ display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 16px; }}
  .stat-box {{ flex: 1; min-width: 120px; background: white; border-radius: 10px; padding: 12px 16px; border: 1px solid #e8eaed; }}
  .stat-box .label {{ font-size: 0.7rem; font-weight: 600; color: #8e98a3; text-transform: uppercase; letter-spacing: 0.04em; }}
  .stat-box .value {{ font-size: 1.4rem; font-weight: 700; color: #0f1419; margin-top: 2px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
  th {{ text-align: left; padding: 8px 12px; background: #f0f2f5; font-weight: 600; color: #536471; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.03em; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid #e8eaed; }}
  .tag {{ display: inline-block; padding: 2px 8px; border-radius: 6px; font-size: 0.75rem; font-weight: 500; }}
  .tag-pass {{ background: #e6f7e6; color: #137333; }}
  .tag-fail {{ background: #fce8e6; color: #c5221f; }}
  .tag-warn {{ background: #fef7e0; color: #b06000; }}
  .footer {{ text-align: center; font-size: 0.75rem; color: #8e98a3; margin-top: 20px; }}
</style>
</head>
<body>
<div class="container">
{content}
<div class="footer">Generated by Symbiotic Cognitive Immune System Agent &mdash; {generated_at}</div>
</div>
</body>
</html>"""


def _section(title: str, body: str) -> str:
    return f'<div class="card"><h2>{title}</h2>{body}</div>'


def _stat_box(label: str, value: str) -> str:
    return f'<div class="stat-box"><div class="label">{label}</div><div class="value">{value}</div></div>'


def generate_benchmark_report(stats: dict, cases: list[dict] | None = None) -> str:
    """Generate a self-contained HTML report for benchmark results."""
    s = stats.get("stats", stats)
    total = s.get("total", 0)
    immune = s.get("immune_activated", 0)
    antibodies = s.get("antibodies_generated", 0)
    anomalies_final = s.get("anomalies_final_state", 0)
    duration = s.get("total_duration", 0)
    detection_rate = stats.get("detection_rate_pct", 0)
    antibody_rate = stats.get("antibody_rate_pct", 0)
    escalations = s.get("escalations", 0)

    stat_row = _stat_box("Total Tests", str(total))
    stat_row += _stat_box("Detection Rate", f"{detection_rate}%")
    stat_row += _stat_box("Immune Activated", str(immune))
    stat_row += _stat_box("Antibody Rate", f"{antibody_rate}%")
    stat_row += _stat_box("Anomalies (final)", str(anomalies_final))
    stat_row += _stat_box("Duration", f"{duration:.1f}s")

    content = f'<div class="stat-row">{stat_row}</div>'
    content += _bar_html("Detection Rate", detection_rate, color="#1a73e8")
    content += _bar_html("Antibody Rate", antibody_rate, color="#0d9488")
    content += _bar_html("Escalation Rate",
                         escalations / total * 100 if total > 0 else 0,
                         color="#ef4444")

    if cases:
        rows = ""
        for c in cases:
            anom_tag = '<span class="tag tag-pass">Yes</span>' if c.get("anomalies", 0) > 0 else '<span class="tag tag-fail">No</span>'
            immune_tag = '<span class="tag tag-pass">Yes</span>' if c.get("immune_active") else '<span class="tag tag-warn">No</span>'
            rows += f"<tr><td>#{c.get('index', '?')}</td><td>{c.get('query', '')[:80]}...</td><td>{anom_tag}</td><td>{immune_tag}</td><td>{c.get('duration', 0):.1f}s</td></tr>"
        content += _section("Test Cases", f'<table><tr><th>#</th><th>Query</th><th>Anomaly</th><th>Immune</th><th>Duration</th></tr>{rows}</table>')

    return _HTML_TEMPLATE.format(
        title="Immune System — Benchmark Report",
        content=content,
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )


def generate_training_report(stats: dict, results: list[dict] | None = None) -> str:
    """Generate HTML report for adversarial training results."""
    total = stats.get("total_queries", 0)
    detected = stats.get("detected", 0)
    recovered = stats.get("recovered", 0)
    avg_score = stats.get("avg_score", 0)
    detection_rate = stats.get("detection_rate", 0)
    recovery_rate = stats.get("recovery_rate", 0)
    epochs = stats.get("scores_by_epoch", [])

    stat_row = _stat_box("Total Queries", str(total))
    stat_row += _stat_box("Detection Rate", f"{detection_rate}%")
    stat_row += _stat_box("Recovery Rate", f"{recovery_rate}%")
    stat_row += _stat_box("Avg Score", f"{avg_score:.2f}")

    content = f'<div class="stat-row">{stat_row}</div>'
    content += _bar_html("Detection", detection_rate, color="#1a73e8")
    content += _bar_html("Recovery", recovery_rate, color="#0d9488")

    if epochs:
        rows = ""
        for ep in epochs:
            rows += f"<tr><td>{ep.get('epoch', '?')}</td><td>{ep.get('queries', 0)}</td><td>{ep.get('detected', 0)}</td><td>{ep.get('recovered', 0)}</td><td>{ep.get('avg_score', 0):.2f}</td></tr>"
        content += _section("Epoch Progress", f'<table><tr><th>Epoch</th><th>Queries</th><th>Detected</th><th>Recovered</th><th>Score</th></tr>{rows}</table>')

    if results:
        rows = ""
        for r in results[-30:]:
            det_tag = '<span class="tag tag-pass">Yes</span>' if r.get("correctly_detected") else '<span class="tag tag-fail">No</span>'
            imm_tag = '<span class="tag tag-pass">Yes</span>' if r.get("immune_activated") else '<span class="tag tag-warn">No</span>'
            rows += f"<tr><td>{r.get('category', '?')[:15]}</td><td>{r.get('query', '')[:60]}...</td><td>{det_tag}</td><td>{imm_tag}</td><td>{r.get('score', 0):.2f}</td></tr>"
        content += _section("Recent Results", f'<table><tr><th>Category</th><th>Query</th><th>Detected</th><th>Immune</th><th>Score</th></tr>{rows}</table>')

    return _HTML_TEMPLATE.format(
        title="Immune System — Training Report",
        content=content,
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )


def generate_metrics_report(metrics_summary: dict) -> str:
    """Generate HTML report from metrics data."""
    s = metrics_summary
    if s.get("status") == "no_data":
        content = '<p style="color:#8e98a3">No metrics data available.</p>'
        return _HTML_TEMPLATE.format(title="Immune System — Metrics Report", content=content,
                                     generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"))

    records = s.get("records", 0)
    success_rate = s.get("success_rate", 0)
    anomaly_rate = s.get("anomaly_rate", 0)
    immune_rate = s.get("immune_activation_rate", 0)
    lat = s.get("latency", {})

    stat_row = _stat_box("Queries", str(records))
    stat_row += _stat_box("Success", f"{success_rate}%")
    stat_row += _stat_box("Anomaly", f"{anomaly_rate}%")
    stat_row += _stat_box("Immune", f"{immune_rate}%")
    stat_row += _stat_box("Avg Latency", f"{lat.get('avg_seconds', 0):.2f}s")
    stat_row += _stat_box("P95 Latency", f"{lat.get('p95_seconds', 0):.2f}s")

    content = f'<div class="stat-row">{stat_row}</div>'
    content += _bar_html("Success Rate", success_rate, color="#22c55e")
    content += _bar_html("Anomaly Rate", anomaly_rate, color="#ef4444")
    content += _bar_html("Immune Activation", immune_rate, color="#7c3aed")

    anomaly_breakdown = s.get("anomaly_breakdown", {})
    if anomaly_breakdown:
        rows = ""
        for src, count in sorted(anomaly_breakdown.items(), key=lambda x: -x[1]):
            rows += f"<tr><td>{src}</td><td>{count}</td></tr>"
        content += _section("Anomaly Sources", f'<table><tr><th>Source</th><th>Count</th></tr>{rows}</table>')

    return _HTML_TEMPLATE.format(
        title="Immune System — Metrics Report",
        content=content,
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )


def save_report(html: str, filename: str | None = None) -> str:
    """Save an HTML report to disk. Returns the file path."""
    os.makedirs(REPORTS_DIR, exist_ok=True)
    if filename is None:
        filename = f"report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.html"
    path = os.path.join(REPORTS_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    logger.info("Report saved: %s", path)
    return path
